### ISSUE TITLE
doc\src\examples\hooks.cpp do not compile in Visual Studio 2017/2019

### ISSUE THREAD

**Issue by hern-chen** [reyreaud-l/threadpool#4]
It looks like the statement
   auto res = pool.run([]() { return 0; });
do not compile with Visual Studio 2017 and 2019.  It seems that returing anything will trigger compilation error.

simple.cpp compiles and builds fine as it runs a avoid function
   auto task = mypool.run([]() { std::cout << "Hello there!" << std::endl; });

**Comment by reyreaud-l** [comment]
Hi!

I am sorry, I don't have a windows machine to test. Could you paste me the full logs of the compiler and the errors ? That would be helpful to attempt to fix it :)

**Comment by hern-chen** [comment]
There is only one compilation error with the template instantiation.
The apparent error seem to be due to the copy instead of move constructor got called for the task (std::packed_task<*>) object.   This could be due to how deque/queue/future/functional are implemented in VS [2017/2019.  I am including the message here and attaching link to associated files in files.zip here [https://1drv.ms/u/s!AnOlf9EuPuX1qzHvoS1AqxQPQEe3?e=luT293](url).
Thanks for sharing the code and for looking at this problem.

D:\misc\ThreadPool\reyreaud-l_threadpool\doc\src\examples>cls

D:\misc\ThreadPool\reyreaud-l_threadpool\doc\src\examples>cl /EHsc /I..\..\..\include hooks.cpp 
hooks.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\functional(1195): error C2280: 'std::packaged_task<task_return_type (void)>::packaged_task(const std::packaged_task<task_return_type (void)> &)': attempting to reference a deleted function
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\future(1755): note: see declaration of 'std::packaged_task<task_return_type (void)>::packaged_task'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\future(1755): note: 'std::packaged_task<task_return_type (void)>::packaged_task(const std::packaged_task<task_return_type (void)> &)': function was explicitly deleted
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\functional(1214): note: see reference to function template instantiation 'std::_Func_impl_no_alloc<std::packaged_task<task_return_type (void)>,_Ret>::_Func_impl_no_alloc<const _Callable&,void>(_Other)' being compiled
        with
        [
            _Ret=void,
            _Callable=std::packaged_task<task_return_type (void)>,
            _Other=const std::packaged_task<task_return_type (void)> &
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\functional(1214): note: see reference to function template instantiation 'std::_Func_impl_no_alloc<std::packaged_task<task_return_type (void)>,_Ret>::_Func_impl_no_alloc<const _Callable&,void>(_Other)' being compiled
        with
        [
            _Ret=void,
            _Callable=std::packaged_task<task_return_type (void)>,
            _Other=const std::packaged_task<task_return_type (void)> &
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\functional(1213): note: while compiling class template member function 'std::_Func_base<_Ret> *std::_Func_impl_no_alloc<std::packaged_task<task_return_type (void)>,_Ret>::_Clone(void *,std::false_type) const'
        with
        [
            _Ret=void
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\functional(1204): note: see reference to function template instantiation 'std::_Func_base<_Ret> *std::_Func_impl_no_alloc<std::packaged_task<task_return_type (void)>,_Ret>::_Clone(void *,std::false_type) const' being compiled
        with
        [
            _Ret=void
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\functional(1061): note: see reference to class template instantiation 'std::_Func_impl_no_alloc<std::packaged_task<task_return_type (void)>,_Ret>' being compiled
        with
        [
            _Ret=void
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\functional(1320): note: see reference to class template instantiation 'std::_Is_large<_Impl>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\functional(1502): note: see reference to function template instantiation 'void std::_Func_class<_Ret>::_Reset<std::packaged_task<task_return_type (void)>>(_Fx &&)' being compiled
        with
        [
            _Ret=void,
            _Fx=std::packaged_task<task_return_type (void)>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\functional(1502): note: see reference to function template instantiation 'void std::_Func_class<_Ret>::_Reset<std::packaged_task<task_return_type (void)>>(_Fx &&)' being compiled
        with
        [
            _Ret=void,
            _Fx=std::packaged_task<task_return_type (void)>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\future(674): note: see reference to function template instantiation 'std::function<void (void)>::function<_Ty,void>(_Fx)' being compiled
        with
        [
            _Ty=std::packaged_task<task_return_type (void)>,
            _Fx=std::packaged_task<task_return_type (void)>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\future(673): note: see reference to function template instantiation 'std::function<void (void)>::function<_Ty,void>(_Fx)' being compiled
        with
        [
            _Ty=std::packaged_task<task_return_type (void)>,
            _Fx=std::packaged_task<task_return_type (void)>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\future(1676): note: see reference to function template instantiation 'std::_Packaged_state<_Ret (void)>::_Packaged_state<_Ty>(_Fty2 &&)' being compiled
        with
        [
            _Ret=void,
            _Ty=std::packaged_task<task_return_type (void)>,
            _Fty2=std::packaged_task<task_return_type (void)>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\future(1675): note: see reference to function template instantiation 'std::_Packaged_state<_Ret (void)>::_Packaged_state<_Ty>(_Fty2 &&)' being compiled
        with
        [
            _Ret=void,
            _Ty=std::packaged_task<task_return_type (void)>,
            _Fty2=std::packaged_task<task_return_type (void)>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xmemory0(881): note: see reference to function template instantiation 'std::packaged_task<void (void)>::packaged_task<_Ty,void>(_Fty2 &&)' being compiled
        with
        [
            _Ty=std::packaged_task<task_return_type (void)>,
            _Fty2=std::packaged_task<task_return_type (void)>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xmemory0(881): note: see reference to function template instantiation 'std::packaged_task<void (void)>::packaged_task<_Ty,void>(_Fty2 &&)' being compiled
        with
        [
            _Ty=std::packaged_task<task_return_type (void)>,
            _Fty2=std::packaged_task<task_return_type (void)>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\deque(1139): note: see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,std::packaged_task<task_return_type (void)>>(_Alloc &,_Objty *const ,std::packaged_task<task_return_type (void)> &&)' being compiled
        with
        [
            _Alloc=std::allocator<ThreadPool::ThreadPool::task_type>,
            _Ty=ThreadPool::ThreadPool::task_type,
            _Objty=ThreadPool::ThreadPool::task_type
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\deque(1137): note: see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,std::packaged_task<task_return_type (void)>>(_Alloc &,_Objty *const ,std::packaged_task<task_return_type (void)> &&)' being compiled
        with
        [
            _Alloc=std::allocator<ThreadPool::ThreadPool::task_type>,
            _Ty=ThreadPool::ThreadPool::task_type,
            _Objty=ThreadPool::ThreadPool::task_type
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\queue(96): note: see reference to function template instantiation 'void std::deque<_Ty,std::allocator<_Ty>>::emplace_back<std::packaged_task<task_return_type (void)>>(std::packaged_task<task_return_type (void)> &&)' being compiled
        with
        [
            _Ty=ThreadPool::ThreadPool::task_type
        ]
..\..\..\include\threadpool.hpp(361): note: see reference to function template instantiation 'void std::queue<ThreadPool::ThreadPool::task_type,std::deque<_Ty,std::allocator<_Ty>>>::emplace<std::packaged_task<task_return_type (void)>>(std::packaged_task<task_return_type (void)> &&)' being compiled
        with
        [
            _Ty=ThreadPool::ThreadPool::task_type
        ]
..\..\..\include\threadpool.hpp(341): note: see reference to function template instantiation 'void ThreadPool::ThreadPool::dispatch_work<std::packaged_task<task_return_type (void)>>(const size_t,TaskType)' being compiled
        with
        [
            TaskType=std::packaged_task<task_return_type (void)>
        ]
hooks.cpp(25): note: see reference to function template instantiation 'std::future<int> ThreadPool::ThreadPool::run<main::<lambda_2d4c5f4a6e98a316199511c7b85de2e4>,>(Function &&)' being compiled
        with
        [
            Function=main::<lambda_2d4c5f4a6e98a316199511c7b85de2e4>
        ]

**Comment by hern-chen** [comment]
I think there is a mismatch between task and task queue.  The tasks queue is defined as
     using task_type = std::packaged_task<void()>; 
     std::queue<task_type> tasks;
but the task to be stored in it is
     auto task = std::packaged_task<task_return_type()>(
              std::bind(std::forward<Function&&>(f), std::forward<Args&&...>(args)...)); 

For the hooks.cpp example, task is std::packaged_task<int()>.

**Comment by reyreaud-l** [comment]
Hey thanks for investigating, sorry I don't have much time available at the moment.
If you want to make a PR to fix it I would gladly appreciate it! Otherwise I'll have a look at it fixing myself when I can.

**Comment by hern-chen** [comment]
Sorry, I don't know how to do a PR - will probably do that when I have free time.  Anyway, this is the diff to fix both issues
diff threadpool.hpp threadpool.h00
147,148c147
< //using task_type = std::packaged_task<void()>;
<   using task_type = std::function<void()>;
---
>   using task_type = std::packaged_task<void()>;
331,333c330,332
<   auto task_ptr = std::make_shared<std::packaged_task<task_return_type()>>(
<     std::bind(std::forward<Function>(f), std::forward<Args>(args)...));
<   auto result = task_ptr->get_future();
---
>   auto task = std::packaged_task<task_return_type()>(
>     std::bind(std::forward<Function&&>(f), std::forward<Args&&...>(args)...));
>   auto result = task.get_future();
342,349c341
<   //Wrap packaged task into lambda void function
<   std::function<void()> wrapper_func = [task_ptr]() {
<    (*task_ptr)();
<   };
<   // what do we have for task_ptr when wrapper_func is run???
<   // who is responsible for freeing task_ptr???
<
<   dispatch_work(idx, wrapper_func);
---
>   dispatch_work(idx, std::move(task));

Thanks again for sharing the code.

**Comment by reyreaud-l** [comment]
Looks related to #5
