### ISSUE TITLE
Compilation error when passing multiple args to ::run 

### ISSUE THREAD

**Issue by hern-chen** [reyreaud-l/threadpool#5]
I got compilation error from Visual Studio 2017 when I tried to run
   void multiply(const int a, const int b)
with ThreadPool pool as
   pool.run(multiply, i, j);

This is resolved by replacing the line
    std::bind(std::forward<Function&&>(f), std::forward<Args&&...>(args)...));
with
   std::bind(std::forward<Function>(f), std::forward<Args>(args)...));
and the arguments are passed properly.

**Comment by reyreaud-l** [comment]
Hey! Sorry for the huge delay in the answer.
Would you mind writing here the compiler output if you still have it ? I don't have a windows box to debug it.

It looks like the types written explicitely are wrong in the forwarding. I would prefer to keep them explicit but to correct them.
Can you try with <Function>(xxx) and <Args...>(xxx) ?
I think this should be correct.

Sorry for the delay again!
